# Generated by Django 3.0 on 2019-09-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ju',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('ju', models.TextField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='fayan',
        ),
    ]
